---
- name: Deploy Login App
  hosts: all
  become: yes

  tasks:
  - name: Ensure Sample Page Removed
    file:
      state: absent
      path: /var/www/html/index.nginx-debian.html

  - name: Ensure App Deployed
    git:
      repo: https://github.com/ravi2krishna/devops-2410.git
      dest: /var/www/html